### ISSUE TITLE
Artisan crashes on running "Designer"

### ISSUE THREAD

**Issue by CommunistWitchDoctor** [artisan-roaster-scope/artisan#156]
On running the Designer function, Artisan crashes with the following error:

```
Traceback (most recent call last):
  File "src/artisanlib/main.py", line 21236, in designerTriggered
  File "src/artisanlib/main.py", line 21239, in startdesigner
  File "src/artisanlib/main.py", line 7894, in designer
  File "src/artisanlib/main.py", line 7963, in designerinit
  File "src/artisanlib/main.py", line 8021, in redrawdesigner
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/scipy/interpolate/__init__.py", line 175, in <module>
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/scipy/interpolate/interpolate.py", line 20, in <module>
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/scipy/linalg/__init__.py", line 186, in <module>
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/scipy/linalg/misc.py", line 5, in <module>
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/scipy/linalg/blas.py", line 196, in <module>
  File "/usr/local/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/share/artisan/scipy.linalg._fblas.so: ELF load command address/offset not properly aligned
[1]    12465 abort (core dumped)  /usr/share/artisan/artisan
/usr/share/artisan/artisan  5.25s user 1.43s system 83% cpu 7.999 total

```

Everything outside of the designer seems to be running normally.

**Comment by CommunistWitchDoctor** [comment]
Sorry, I've discovered this was a problem with the AUR package and not with Artisan by testing the same issue on a clean Ubuntu live cd. Closing the issue.

Note for other Arch users, the package has now been fixed in the AUR.
